candy_list = [
"Abba-Zabba",
"Airheads",
"Andes Mint",
"Atomic Fireball",
"Bazooka Gum",
"Big Hunk",
"Bit-O-Honey",
"Black Cow",
"Black Jack Gum",
"Blow Pop",
"Boston Baked Beans",
"Bottle Caps",
"Bubble Tape",
"Cadbury Egg",
"Candy Buttons",
"Candy Cigarettes",
"Candy Corn",
"Candy Necklace",
"Charleston Chew",
"Charms",
"Chick-O-Stick",
"Chiclets",
"Chuckles",
"Cinnamon Bears",
"Circus Peanuts",
"Cow Tales",
"Crybabies",
"Dots",
"Dum Dums Pop",
"Everlasting Gobstopper",
"Fun Dip",
"Good and Plenty",
"Googoo Cluster",
"Gum Cigars",
"Gumdrops",
"Gummi Bears",
"Gushers",
"Hershey's Kiss",
"Hot Tamales",
"Jawbreaker",
"Jelly Belly Jelly Beans",
"Jolly Rancher",
"Jujubes",
"Jujyfruits",
"Junior Mints",
"Laffy Taffy",
"Lemonhead",
"Lifesavers",
"M&M's",
"Mamba",
"Marathon",
"Mike and Ike",
"Milk Duds",
"Necco Wafers",
"Nerds",
"Now and Later",
"Oompas",
"Orange Slices",
"Orangehead",
"Peeps",
"Pez",
"Pixie Stix",
"Pocky",
"Pop Rocks",
"Raisinets",
"Razzles",
"Red Hots",
"Red Vines",
"Reese's Peanut Butter Cups",
"Reese's Pieces",
"Ring Pop",
"Rolo",
"Runts",
"Sixlets",
"Skittles",
"Slap Stix",
"Slo Poke",
"Smarties",
"Sno-Caps",
"Sour Patch Kids",
"Spree",
"Starburst",
"Sugar Babies",
"Sugar Daddy",
"Swedish Fish",
"Sweetarts",
"Tootsie Pop",
"Tootsie Roll",
"Twizzlers",
"Warheads",
"Wax Bottles",
"Wax Lips",
"Werther's Original",
"Whistle Pop",
"York Peppermint Pattie",
"Zotz",
"Tiny Tarts",
"Valomilk",
"Whoppers",
"Zours"
]
